### ISSUE TITLE
php apm 1.6.1 segfaults on a zend error/php warning

### ISSUE THREAD

**Issue by waynegemmell** [elastic/apm-agent-php#831] opened 2022-12-01 13:14 UTC
**Describe the bug**
When inserting a continue into a for loop APM segfaults. PHP generally shows a warning, When I ran gdb it seems that zend throws and error. I really don't think that apm should die on a warning without any useful information being exposed.

**To Reproduce**
The below code triggers the segfault. 

```
<?php

$alist = ['apple', 'banana', 'lemon', 'lime'];

print('Starting'. "\n");

foreach ($alist as $item) {
        switch ($item) {
                case 'apple':
                        print($item . "\n");
                        break;
                case 'banana':
                        print("more\n");
                        continue;
                default:
                        print("default\n");
        }
}
print("Ended\n");

```
Without APM
`PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/wayne/test.php on line 14
`With APM
`Segmentation fault
`
**Expected behavior**
The php warning should be relayed to the logs somewhere. 

GDB initial snippet

```
Reading symbols from /usr/sbin/php-fpm7.4...
Reading symbols from /usr/lib/debug/.build-id/4c/7489f921fc631b72accb27206c39024829c946.debug...
[New LWP 2076609]
[New LWP 2076638]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php-fpm: pool www                                                            '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f19d9243a1e in __vfscanf_internal (s=s@entry=0x7fffc73555d0, format=format@entry=0x7f19d93958f7 "%hu%n:%hu%n:%hu%n", argptr=argptr@entry=0x7fffc73555b8, mode_flags=mode_flags@entry=2)
    at vfscanf-internal.c:278
278	vfscanf-internal.c: No such file or directory.
[Current thread is 1 (Thread 0x7f19d717ba00 (LWP 2076609))]
```
GDB Offending lines

```
#42545 0x00007f19d3fc9836 in callPhpFunction () from /opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so
#42546 0x00007f19d3fc9e26 in callPhpFunctionRetVoid () from /opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so
#42547 0x00007f19d3fc772a in onPhpErrorToTracerPhpPart () from /opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so
#42548 0x00007f19d3fb60e7 in elasticApmZendErrorCallbackImpl () from /opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so
#42549 0x00007f19d3fb62de in elasticApmZendErrorCallback () from /opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so
#42550 0x000055a377dcf7b3 in zend_error_va_list (type=type@entry=2, error_filename=0x7f19c3eb3108 "/var/local/sac/app/Models/MemberBasket.php", error_lineno=292, format=format@entry=0x55a378072440 "\"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue %ld\"?", args=args@entry=0x7fffc7b4faf0) at ./Zend/zend.c:1319
#42551 0x000055a377dcfd97 in zend_error (type=type@entry=2, format=format@entry=0x55a378072440 "\"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue %ld\"?") at ./Zend/zend.c:1480

```

PHP FPM logs

`[01-Dec-2022 10:33:13] WARNING: [pool www] child 2094944 exited on signal 11 (SIGSEGV - core dumped) after 33252.924112 seconds from start`

**Comment by xyu** [comment] 2022-12-13 19:37
We are also running into this issue on 1.6.2.

**Comment by waynegemmell** [comment] 2022-12-14 09:43
We tested 1.7.0 with the same issues. I just didn't mention it because it's marked as unstable.

**Comment by estolfo** [comment] 2022-12-14 09:48
Thanks @waynegemmell for the info, we are looking into it and should have an update soon!

**Comment by estolfo** [comment] 2022-12-16 11:53
Hi @xyu thank you for the extra details and help in investigating this issue. We are currently investigating on our side and should have an update soon. Thanks for your patience!

**Comment by SergeyKleyman** [comment] 2022-12-19 14:43
@xyu Thank you very much for analysis. You are absolutely correct and indeed the root cause seems to be the timing - PHP error occurs at a point when PHP part of the agent cannot be invoked. We encountered similar situation in #737 and we implemented a fix for it (#797) by reversing control flow - instead of having C part of the agent push notification about the error to PHP part we buffer the notification at C part and have PHP part poll for it at key points (begin/end of span/transaction, etc.). This fix was already part of 1.7.0 release but its implementation had some bugs which we are trying to fix in https://github.com/elastic/apm-agent-php/pull/834. We have [the fix candidate](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-php%2Fapm-agent-php-mbp/detail/PR-834/8/artifacts/) and I tested it on the scenario in this issue as well and it seems to fix it.

@waynegemmell, @xyu Could you please try [[the fix candidate](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-php%2Fapm-agent-php-mbp/detail/PR-834/8/artifacts/) and let us know if it fixes the issue for you?

**Comment by mcouillard** [comment] 2022-12-19 22:04
Maybe related, but this fix candidate version allowed our PHP 8.1 Zend/Laminas site to again work with APM, where prior with 1.3 through 1.6 it failed after our upgrade from PHP 7.4.

**Comment by xyu** [comment] 2022-12-19 23:49
I can also confirm the fix candidate indeed resolve the segfault issue, the PHP warning is being handled properly now and the trace gets sent to APM Server when running this sample file:

```php
<?php

switch ( 1 ) {
	case 1:
		continue;
}

echo 'Done' . PHP_EOL;
```

**Comment by waynegemmell** [comment] 2022-12-20 08:01
I haven't managed to download the test release but @xyu seems to have validated it.

**Comment by waynegemmell** [comment] 2022-12-20 09:23
Thank you

**Comment by SergeyKleyman** [comment] 2023-01-09 09:13
Fixed by #834

**Closed by SergeyKleyman** 2023-01-09 09:13 UTC
Labels: bug, agent-php

**Comment by SergeyKleyman** [comment] 2023-01-16 13:45
@doyelese [1.7.1](https://github.com/elastic/apm-agent-php/releases/tag/v1.7.1) (which includes the fix for this issue) has been just released.

**Comment by waynegemmell** [comment] 2023-01-16 14:20
Thanks
