### ISSUE TITLE
segmentation fault with latest release

### ISSUE THREAD

**Issue by fplotnikov** [elastic/apm-agent-php#856] opened 2023-01-28 20:36 UTC
Installation on any version of apm agent cause a "segmentation fault"  error in LAMP setup. 

**To Reproduce**
OS: Red Hat Enterprise Linux Server release 7.9
Apache: httpd-2.4.6-97.0.7.el7_9.5
PHP: php81-8.1-1
Agent: apm-agent-php-1.7.1-1

The quickest option to reproduce the issue is to perform: "service httpd  reload" a few times and then start using the PHP application.
In real life, the agent starts reporting metrics to the server, and in 1-2 days after performing the embedded log rotation procedure apache with PHP module starts failing with a "segmentation fault" 
Restart apache and killing all active threads can help to recover operations for some time.

We tested all versions starting from 1.6.1 - the same behavior including the last release.

**Comment by alexbaileyuk** [comment] 2023-02-13 14:59
Afraid to say we're having the same issue with PHP 7.4 and release version 1.7.1.

Application is a Symfony application running in `php:7.4-fpm-alpine`. We have libcurl installed as listed as a dependency and are installing APM using:

```
RUN wget "https://github.com/elastic/apm-agent-php/releases/download/v1.7.1/apm-agent-php_1.7.1_all.apk" && \
    apk add --no-cache --allow-untrusted ./apm-agent-php_1.7.1_all.apk && rm ./apm-agent-php_1.7.1_all.apk
```

**Comment by apetrosyan1613** [comment] 2023-03-07 15:46
It's critical. You released php8.2 support, but this is bug still relevant and we can't use older versions with php8.2.

**Comment by intuibase** [comment] 2023-03-08 21:09
Hey all, 
Could you please provide more details how to reproduce issue or provide docker image which reproduces it?

**Comment by apetrosyan1613** [comment] 2023-03-09 09:11
> Hey all, Could you please provide more details how to reproduce issue or provide docker image which reproduces it?


Hey!

We use ubuntu:focal docker image with php8.2 installed.

Something like:

```
FROM ubuntu:focal

ENV TERM=linux

ENV DEBIAN_FRONTEND=noninteractive

# Install Ondrej repos for Ubuntu focal, PHP8.2, composer and selected extensions - better selection than
# the distro's packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends gnupg \
    && echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main" > /etc/apt/sources.list.d/ondrej-php.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        ca-certificates \
        git \
        curl \
        unzip \
        php8.2-apcu \
        php8.2-cli \
        php8.2-curl \
        php8.2-mbstring \
        php8.2-opcache \
        php8.2-readline \
		php8.2-gd \
        php8.2-bcmath \
		libpng-dev \
		zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* ~/.composer

RUN curl -L https://github.com/elastic/apm-agent-php/releases/download/v1.8.0/apm-agent-php_1.8.0_all.deb -o apm-agent-php_1.8.0_all.deb && \
        dpkg -i apm-agent-php_1.8.0_all.deb && rm apm-agent-php_1.8.0_all.deb

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

CMD ["php", "-a"]

```
elastic-apm-agent: 1.8.0
We sent some requests to laravel(9.0) application and when elastic apm is enabled PHP is generating a lot of core dump files

**Comment by moh2a** [comment] 2023-03-24 17:11
Hello, I'am having the same issue with 1.8.1 and 1.8.0 version (not tested others) for a symfony application

**Comment by gminiba** [comment] 2023-04-11 09:14
same problem here with all versions tested including the latest one 1.8.1

**Comment by intuibase** [comment] 2023-04-24 11:19
Hey @apetrosyan1613 , @moh2a , @gminiba, @fplotnikov, @alexbaileyuk 

Could you please test the latest release (https://github.com/elastic/apm-agent-php/releases/tag/v1.8.3) of the agent on your environment and confirm that #913  has fixed the problem?

Best regards
Pawel

**Comment by alexbaileyuk** [comment] 2023-04-24 11:48
Can you provide a change log for that since there doesn't appear to be one in the elastic docs?

**Comment by moh2a** [comment] 2023-04-24 11:51
Sorry but for me it is not fixed for both 1.8.2 and 1.8.3 ... Maybe the others

**Comment by intuibase** [comment] 2023-04-24 12:38
@alexbaileyuk https://www.elastic.co/guide/en/apm/agent/php/master/release-notes-v1.8.3.html

**Comment by Dave221842** [comment] 2023-04-25 19:09
@intuibase - still same issues. Running 1.8.3. Tested yesterday

Tue Apr 25 10:03:08.426391 2023] [core:notice] [pid 94327] AH00052: child pid 49215 exit signal Segmentation fault (11)
[Tue Apr 25 10:03:22.441006 2023] [core:notice] [pid 94327] AH00052: child pid 49246 exit signal Segmentation fault (11)
[Tue Apr 25 10:03:23.442266 2023] [core:notice] [pid 94327] AH00052: child pid 49245 exit signal Segmentation fault (11)
[Tue Apr 25 10:03:46.445933 2023] [core:notice] [pid 94327] AH00052: child pid 49247 exit signal Segmentation fault (11)
[Tue Apr 25 10:03:46.445977 2023] [core:notice] [pid 94327] AH00052: child pid 49248 exit signal Segmentation fault (11)
[Tue Apr 25 10:05:20.553666 2023] [core:notice] [pid 94327] AH00052: child pid 50704 exit signal Segmentation fault (11)
[Tue Apr 25 10:05:23.564561 2023] [core:notice] [pid 94327] AH00052: child pid 50712 exit signal Segmentation fault (11)
[Tue Apr 25 10:05:23.564620 2023] [core:notice] [pid 94327] AH00052: child pid 50713 exit signal Segmentation fault (11)
[Tue Apr 25 10:05:27.569127 2023] [core:notice] [pid 94327] AH00052: child pid 50721 exit signal Segmentation fault (11)
[Tue Apr 25 10:05:27.569198 2023] [core:notice] [pid 94327] AH00052: child pid 50722 exit signal Segmentation fault (11)
[Tue Apr 25 10:05:35.578021 2023] [core:notice] [pid 94327] AH00052: child pid 50723 exit signal Segmentation fault (11)
[Tue Apr 25 10:05:36.579158 2023] [core:notice] [pid 94327] AH00052: child pid 50724 exit signal Segmentation fault (11)
[Tue Apr 25 10:07:31.708520 2023] [core:notice] [pid 94327] AH00052: child pid 51679 exit signal Segmentation fault (11)

**Comment by intuibase** [comment] 2023-04-26 19:53
Hey @Dave221842 

Thank you for testing. Is it possible for you to catch a core dump file and deliver it to me?

I'm working on a tool which will help collect all data needed to analyze core dump files - I'll deliver detailed instructions  

Best regards,
Pawel

**Comment by Dave221842** [comment] 2023-05-01 15:25
@intuibase - send me your e-mail and i will send the dump to you.

D.

**Comment by alexbaileyuk** [comment] 2023-05-03 14:04
@intuibase this error is still happening on 1.8.3 for us unfortunately. Symfony Process calls `wkhtml2pdf` which appears to be resulting in a segfault.

**Comment by chrismuiruriz** [comment] 2023-05-21 13:30
I'm facing the same issue as well, any luck with the solution?

**Comment by intuibase** [comment] 2023-05-22 08:43
Hey @Dave221842 
Sorry for late response, please contact me through pawel.filipczak at elastic.co
I'll send you upload server details

Best regards,
Pawel

**Comment by intuibase** [comment] 2023-05-23 10:53
Hey @alexbaileyuk, @chrismuiruriz  @Dave221842 

It looks like we're mixing at least two cases here. In 1.8.4 release composer related issues should be solved. Please try it out and let me know if it solved issue for you. 

wkhtml2pdf issue from @alexbaileyuk may be different.

Could you please try to fetch core dump from your system?
You can use a tool I implemented:
https://github.com/intuibase/core-dump-collector

I'm interested in result of crash_collector.sh. For the script to work correctly, the tools described in the header of the script must be installed. Additionally core dump limit must be set to unlimited (read more here https://www.akadia.com/services/ora_enable_core.html)

If you manage to get the core dump, please let me know and I will provide an upload link for you.

Best regards,
Pawel

**Comment by intuibase** [comment] 2023-06-05 13:44
Hey @alexbaileyuk  @chrismuiruriz  @Dave221842 

Issue was fixed with 1.8.4 release. Please update agent and verify if it solves it on your environment.

Best regards,
Pawel

**Closed by intuibase** 2023-06-05 13:44 UTC
Labels: bug, agent-php

**Comment by alexbaileyuk** [comment] 2023-06-05 13:49
Hi sorry about the delays in response, we've been testing this internally and it appears that it is resolved for us on 1.8.4. we haven't finished checking yet but initial results look good.

**Comment by intuibase** [comment] 2023-06-06 07:19
Hi. Thank you for the feedback

**Comment by intuibase** [comment] 2023-06-12 12:36
Hi @gminiba @moh2a @fplotnikov @chrismuiruriz @apetrosyan1613 

Could you please try with 1.8.4 release and let us know if it solved issue for you?

Regards,
Pawel

**Comment by gminiba** [comment] 2023-06-25 18:44
with 1.8.4 we don't see the issue as well, thank you

**Comment by chrismuiruriz** [comment] 2023-06-26 12:29
Version 1.8.4 is working okay
