### ISSUE TITLE
Add support for MongoDB

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#700] opened 2022-06-01 09:20 UTC
**Useful links**
- [MongoDB (PHPLIB) - Application Performance Monitoring (APM)](https://www.php.net/manual/en/mongodb.tutorial.apm.php)

**Comment by intuibase** [comment] 2024-03-12 10:04
It is duplicate of #1046

**Closed by intuibase** 2024-03-12 10:04 UTC
Labels: enhancement, from a real user, agent-php, triaged, priority: medium
