### ISSUE TITLE
Random Notice of Undefined variable: _SERVER

### ISSUE THREAD

**Issue by damienalexandre** [elastic/apm-agent-php#77] opened 2020-07-02 14:15 UTC
Hi!
I hope I'm not reporting bug "too soon" as there is no official release yet. I played with the agent today and I get a **random** Notice.

I run a Docker stack with:
- PHP 7.4.7
- PHP-FPM and Ngnix
- Debian based

I just run a simple `index.php`:

```
<?php

echo "Hello world\n";
```

And I get this notice:

> Notice: Undefined variable: _SERVER in /apm-agent-php-master/src/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php on line 84

The fact it's random bother me - I don't understand how to reproduce every-time.

**When it happen the data are not send to the APM Server**.

You can try with this branch: https://github.com/jolicode/docker-starter/pull/104
As you can see I use the `elastic_apm.bootstrap_php_part_file=/apm-agent-php-master/src/bootstrap_php_part.php` configuration.

```
git clone git@github.com:jolicode/docker-starter.git
git checkout php-apm
echo '127.0.0.1 app.test' | sudo tee -a /etc/hosts
pipenv install
pipenv shell
inv start
```

Then go to https://app.test/

Thanks a lot for this agent, I'm looking forward being able to use it!

**Comment by SergeyKleyman** [comment] 2020-07-14 16:45
Hi @damienalexandre 

Thank you for the feedback - it's very valuable!

Do you think it might be related to this bug (https://bugs.php.net/bug.php?id=69081)? Although it says that the bug is fixed in PHP 7.2 but after searching the Internet I do see that people still complain about it, for example [here](https://stackoverflow.com/questions/54509003/undefined-variable-server) although the post is recent (2019) but it doesn't say which PHP version exhibits the issue.

Regardless I'll try the proposed workarounds. I wonder if the root cause is in the way `$_SERVER` is used at https://github.com/elastic/apm-agent-php/blob/c1ce2c064bdbe95592a7e5a75623040c818c87bc/src/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php#L84
instead of something like `$_SERVER['REQUEST_URI']`.

Can you please try the workaround proposed at https://odd.blog/2015/02/12/php-notice-undefined-variable-_server-in/ (setting `auto_globals_jit` to `off` in `php.ini`)?

**Comment by damienalexandre** [comment] 2020-07-14 19:22
I think you found the bug :+1: Adding `auto_globals_jit = Off` did fix the issue and no random _Undefined variable: _SERVER_ appears anymore :tada:

**Comment by SergeyKleyman** [comment] 2020-07-15 06:14
Great, I'm glad it helped. If you don't mind, I would like to keep this issue open to try and find a solution that won't require changing `php.ini`.
Thank you for your feedback, it will definitely help in working on the out-of-the-box solution.

**Comment by SergeyKleyman** [comment] 2021-03-08 13:27
It seems the same issue was brought up at https://discuss.elastic.co/t/error-in-apm-php-agent/265999 so it might be worth looking for out-of-the-box solution that won't require changing php.ini.

**Closed** 2021-04-06 11:31 UTC
Labels: agent-php, bug
