### ISSUE TITLE
zend_mm_heap corrupted

### ISSUE THREAD

**Issue by lesecho** [elastic/apm-agent-php#306] opened 2020-11-26 03:29 UTC
1. 
system:
uname -a
Linux VM-0-14-centos 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

php version:
PHP 7.2.32 (cli) (built: Aug  8 2020 16:43:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.1, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.2.32, Copyright (c) 1999-2018, by Zend Technologies

apm agent php version:
apm-agent-php-1.0.0_beta1-1.noarch.rpm

2. install agent:
rpm -ivh apm-agent-php-1.0.0_beta1-1.noarch.rpm
3. php.ini :
extension=/opt/elastic/apm-agent-php/extensions/elastic_apm-20170718.so
elastic_apm.bootstrap_php_part_file=/opt/elastic/apm-agent-php/src/bootstrap_php_part.php
elastic_apm.server_url=xxx.ccc.vvv.bbb:8200
elastic_apm.service_name=web2

4.  error:
php -m | grep apm
**zend_mm_heap corrupted**

5.  reload or restart php-fpm(no error):
systemctl reload php-fpm  
systemctl restart php-fpm

no error in php-fpm.log:
[26-Nov-2020 11:22:04] NOTICE: Reloading in progress ...
[26-Nov-2020 11:22:04] NOTICE: reloading: execvp("/path/72/sbin/php-fpm", {"/path/72/sbin/php-fpm", "--daemonize", "--fpm-config", "/path/72/etc/php-fpm.conf", "--pid", "/path/72/var/run/php-fpm.pid"})
[26-Nov-2020 11:22:04] NOTICE: using inherited socket fd=8, "/tmp/php-cgi-72.sock"
[26-Nov-2020 11:22:04] NOTICE: using inherited socket fd=8, "/tmp/php-cgi-72.sock"
[26-Nov-2020 11:22:04] NOTICE: fpm is running, pid 15649
[26-Nov-2020 11:22:04] NOTICE: ready to handle connections

[26-Nov-2020 11:22:16] NOTICE: Finishing ...
[26-Nov-2020 11:22:16] NOTICE: exiting, bye-bye!
[26-Nov-2020 11:22:17] NOTICE: fpm is running, pid 15729
[26-Nov-2020 11:22:17] NOTICE: ready to handle connections

set "opcache.enable_cli=0",but still not working

is this a bug?

**Comment by SergeyKleyman** [comment] 2020-11-30 06:35
I suspect the problem is the combination of Elastic APM extension and ionCube. It was already brought up in https://github.com/elastic/apm-agent-php/issues/123.

Would it possible for you try without ionCube to verify that it's indeed the root cause? I would like to add a note to the documentation drawing attention to this limitation.

**Comment by SergeyKleyman** [comment] 2021-04-12 09:09
Do you mind I close this issue? We can always re-open it in the future if the need arises.

**Comment by AshanCG** [comment] 2021-07-21 21:38
> I suspect the problem is the combination of Elastic APM extension and ionCube. It was already brought up in #123.
> 
> Would it possible for you try without ionCube to verify that it's indeed the root cause? I would like to add a note to the documentation drawing attention to this limitation.

@SergeyKleyman we can confirm the issue indeed with enabling the ionCube. When we disable ionCube, APM agent capture and process the data to APM-Server without any issue. Still with https://github.com/elastic/apm-agent-php/releases/tag/v1.2 (v 1.2) we are experiencing the issue of zend_mm_heap corrupted.

**Comment by nhadsall** [comment] 2022-01-14 19:38
I am also experiencing the same conflict.

**Comment by VlaVDan** [comment] 2022-02-08 09:08
system:
uname -a
Linux 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

php version:
PHP 7.4.27 (cli) (built: Dec 20 2021 21:28:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.27, Copyright (c), by Zend Technologies

apm agent php version:
apm-agent-php_1.3.1_all.deb

Fatal error in apache log, app crashed:
[php7:error] [pid 1547493] PHP Fatal error:  Allowed memory size of 3246391296 bytes exhausted (tried to allocate 9223372043240463144 bytes) in /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php on line 133
zend_mm_heap corrupted

**Comment by SergeyKleyman** [comment] 2022-08-29 11:41
@nhadsall @VlaVDan Could you please check if you still experiencing the issue with [the latest release (v.16)](https://github.com/elastic/apm-agent-php/releases/tag/v1.6) and if so could you please share a simple docker image definition that reproduces this issue?

**Comment by outfoxer** [comment] 2022-10-12 18:10
Hi, @SergeyKleyman I also have this issue with v1.6.1

**Comment by georgesouzafarias** [comment] 2022-10-25 21:24
Same issue here, v1.6.1 and PHP 7.4, 8.0 and 8.1.

**Comment by Hostert** [comment] 2023-05-02 14:40
Same here.

Is there an ETA to #740?

**Comment by SergeyKleyman** [comment] 2023-08-01 09:00
We are closing it since there is no recent updates. Please re-open if it is still occurs with the latest version of the agent.

**Closed by SergeyKleyman** 2023-08-01 09:00 UTC
Labels: bug, agent-php

**Comment by Ashmin77** [comment] 2024-10-31 14:05
Same issue here. Experiencing compatibility problems ionCube and apm with version v1.14.1 and PHP 7.2
